import { AlertTriangleIcon, BotIcon, FileTextIcon } from 'lucide-react';

import type { RecipeDraft } from '@opendish/contracts';

import { RecipeEditorForm } from '@/features/recipe-editor';
import type { RecipeFormValues } from '@/features/recipe-editor';
import { useRecipeMutation } from '@/features/recipe-editor';

import { draftToFormValues } from './draft-to-form-values.ts';
import type { ExtractionMethod } from './import-recipe-api.ts';

export type DraftOrigin = 'imported' | 'ai_generated';

export interface ReviewScreenProps {
  draft: RecipeDraft;
  origin: DraftOrigin;
  extractionMethod?: ExtractionMethod;
  onDiscard: () => void;
}

function bannerForOrigin(
  origin: DraftOrigin,
  extractionMethod: ExtractionMethod | undefined,
) {
  if (origin === 'ai_generated') {
    return {
      icon: BotIcon,
      title: 'Generated by AI — please review carefully',
      description:
        'AI-generated content may be incomplete or incorrect. Edit any field before saving.',
      variant: 'warning' as const,
    };
  }
  if (extractionMethod === 'structured_markup') {
    return {
      icon: FileTextIcon,
      title: 'Extracted from structured page data',
      description:
        'The page published standard recipe markup. You can still edit anything before saving.',
      variant: 'info' as const,
    };
  }
  return {
    icon: AlertTriangleIcon,
    title: 'Extracted by AI — please review carefully',
    description:
      'AI-generated content may be incomplete or incorrect. Edit any field before saving.',
    variant: 'warning' as const,
  };
}

export function ReviewScreen({
  draft,
  origin,
  extractionMethod,
  onDiscard,
}: ReviewScreenProps) {
  const mutation = useRecipeMutation();

  const initialValues: RecipeFormValues = draftToFormValues(draft);

  const handleSubmit = async (
    parsedDraft: RecipeDraft,
    imageFile: File | null,
  ) => {
    await mutation.mutateAsync({
      draft: {
        ...parsedDraft,
        recipeId: null,
        changeKind: 'manual_edit',
        userId: null,
        origin,
        imagePath: null,
      },
      imageFile,
    });
  };

  const banner = bannerForOrigin(origin, extractionMethod);
  const BannerIcon = banner.icon;
  const title =
    origin === 'ai_generated'
      ? 'Review AI-generated recipe'
      : 'Review imported recipe';
  const submitLabel =
    origin === 'ai_generated'
      ? 'Save generated recipe'
      : 'Save imported recipe';
  const discardLabel =
    origin === 'ai_generated'
      ? 'Discard and return to conversation'
      : 'Discard and start over';
  const showAiEstimateNote =
    origin === 'ai_generated' || extractionMethod === 'ai';

  return (
    <section className="flex flex-col gap-6" aria-labelledby="review-title">
      <div className="flex items-start justify-between gap-4">
        <h1 id="review-title" className="text-2xl font-semibold tracking-tight">
          {title}
        </h1>
      </div>

      <div
        className={`flex items-start gap-3 rounded-lg border px-4 py-3 ${
          banner.variant === 'info'
            ? 'border-border bg-muted text-foreground'
            : 'border-destructive/30 bg-destructive/5 text-destructive'
        }`}
        role="status"
        aria-live="polite"
      >
        <BannerIcon className="mt-0.5 size-5 shrink-0" aria-hidden />
        <div>
          <p className="font-medium">{banner.title}</p>
          <p className="text-sm opacity-90">{banner.description}</p>
        </div>
      </div>

      <RecipeEditorForm
        initialValues={initialValues}
        onSubmit={handleSubmit}
        isSubmitting={mutation.isPending}
        submitLabel={submitLabel}
        cancelTo={origin === 'ai_generated' ? '/generate' : '/import'}
        onCancel={origin === 'ai_generated' ? onDiscard : undefined}
        aiEstimateNote={
          showAiEstimateNote
            ? 'AI-generated values are estimates, please review.'
            : undefined
        }
      />

      <div className="flex justify-center">
        <button
          type="button"
          onClick={onDiscard}
          disabled={mutation.isPending}
          className="text-sm text-muted-foreground underline-offset-4 hover:text-foreground hover:underline disabled:pointer-events-none"
        >
          {discardLabel}
        </button>
      </div>
    </section>
  );
}
