import { spawn, spawnSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const GENERATED_MARKER = '# Generated by OpenDish local profile scripts.';
const DEFAULT_APP_URL = 'http://127.0.0.1:5173';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const repoRoot = path.resolve(__dirname, '..', '..');
export const defaultEnvFile = path.join(repoRoot, 'apps', 'web', '.env.local');

export function logStep(message) {
  console.log(`\n==> ${message}`);
}

export function logInfo(message) {
  console.log(message);
}

export function parseArgs(argv) {
  const args = {
    flags: new Set(),
    values: new Map(),
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith('--')) continue;

    const equalsIndex = arg.indexOf('=');
    if (equalsIndex !== -1) {
      args.values.set(arg.slice(0, equalsIndex), arg.slice(equalsIndex + 1));
      continue;
    }

    const next = argv[index + 1];
    if (next && !next.startsWith('--')) {
      args.values.set(arg, next);
      index += 1;
      continue;
    }

    args.flags.add(arg);
  }

  return args;
}

export function hasFlag(args, name) {
  return args.flags.has(name);
}

export function getValue(args, name, fallback = undefined) {
  return args.values.get(name) ?? fallback;
}

export function runCommand(command, commandArgs, options = {}) {
  const result = spawnSync(command, commandArgs, {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    ...options,
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    const stderr = (result.stderr ?? '').trim();
    const stdout = (result.stdout ?? '').trim();
    const detail =
      stderr || stdout || `command exited with status ${result.status}`;
    throw new Error(`${command} ${commandArgs.join(' ')} failed: ${detail}`);
  }

  return {
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
  };
}

export function runStreamingCommand(command, commandArgs, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, commandArgs, {
      cwd: repoRoot,
      stdio: 'inherit',
      ...options,
    });

    child.on('error', reject);
    child.on('exit', (code, signal) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(
        new Error(
          `${command} ${commandArgs.join(' ')} exited with ${
            signal ? `signal ${signal}` : `status ${code}`
          }`,
        ),
      );
    });
  });
}

export function extractJsonObject(output) {
  const trimmed = output.trim();
  const start = trimmed.indexOf('{');
  if (start === -1) {
    throw new Error('Expected JSON output from Supabase CLI.');
  }

  return JSON.parse(trimmed.slice(start));
}

export function ensureDocker() {
  logStep('Checking Docker availability');
  try {
    const { stdout } = runCommand('docker', [
      'info',
      '--format',
      '{{.ServerVersion}}',
    ]);
    logInfo(`Docker server ${stdout.trim()} is available.`);
  } catch (error) {
    throw new Error(
      `Docker is required for the local Supabase profile. Ensure the daemon is running and your user can access the Docker socket. ${error.message}`,
      { cause: error },
    );
  }
}

export function startSupabase() {
  logStep('Starting the local Supabase stack');
  runCommand('pnpm', ['supabase', 'start']);
}

export function stopSupabase(options = {}) {
  logStep(
    options.noBackup
      ? 'Stopping the local Supabase stack and clearing local volumes'
      : 'Stopping the local Supabase stack',
  );
  const args = ['supabase', 'stop'];
  if (options.noBackup) {
    args.push('--no-backup');
  }
  try {
    runCommand('pnpm', args);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (
      message.includes('LegacyStopContainerError') ||
      message.includes('No such container') ||
      message.includes('no containers to stop')
    ) {
      logInfo(
        'Supabase local containers were already absent; continuing with a fresh start.',
      );
      return;
    }
    throw error;
  }
}

export function resetLocalDatabase() {
  logStep('Resetting the local database to committed migrations');
  runCommand('pnpm', ['supabase', 'db', 'reset', '--local', '--yes']);
}

export function getSupabaseStatus() {
  const { stdout } = runCommand('pnpm', ['supabase', 'status', '-o', 'json']);
  const status = extractJsonObject(stdout);
  if (!status.API_URL || !status.PUBLISHABLE_KEY) {
    throw new Error(
      'Supabase CLI status did not include the local API URL and publishable key.',
    );
  }

  return {
    ...status,
    // CLI 2.115 no longer emits FUNCTIONS_URL in JSON. Edge Functions remain
    // available through the API gateway under the stable /functions/v1 path.
    FUNCTIONS_URL: status.FUNCTIONS_URL ?? `${status.API_URL}/functions/v1`,
  };
}

export function listEdgeFunctions() {
  const functionsDir = path.join(repoRoot, 'supabase', 'functions');
  return readdirSync(functionsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter(
      (name) =>
        !name.startsWith('_') &&
        existsSync(path.join(functionsDir, name, 'index.ts')),
    );
}

function sanitizeEnvContent(content) {
  return content.replace(/\r\n/g, '\n').trim();
}

function buildEnvFileContent(status) {
  return [
    GENERATED_MARKER,
    '# Local Supabase profile for OpenDish.',
    '# Re-run `pnpm setup:local` whenever the CLI rotates the local publishable key.',
    `VITE_SUPABASE_URL=${status.API_URL}`,
    `VITE_SUPABASE_PUBLISHABLE_KEY=${status.PUBLISHABLE_KEY}`,
    '',
  ].join('\n');
}

export function writeLocalEnvFile(status, options = {}) {
  const envFile = path.resolve(options.envFile ?? defaultEnvFile);
  const shouldWrite = options.write !== false;

  if (!shouldWrite) {
    return { envFile, wrote: false, backedUpTo: null };
  }

  const content = buildEnvFileContent(status);
  const existing = existsSync(envFile) ? readFileSync(envFile, 'utf8') : null;
  const normalizedExisting = existing ? sanitizeEnvContent(existing) : null;
  const normalizedNext = sanitizeEnvContent(content);
  let backedUpTo = null;

  if (existing && normalizedExisting !== normalizedNext) {
    const isGenerated = existing.includes(GENERATED_MARKER);
    if (!isGenerated && !options.forceEnv && !options.backupManagedEnv) {
      throw new Error(
        `Refusing to overwrite ${path.relative(repoRoot, envFile)} because it does not look generated for the local profile. Re-run with --backup-managed-env or --force-env.`,
      );
    }

    if (!isGenerated && options.backupManagedEnv) {
      const stamp = new Date().toISOString().replaceAll(':', '-');
      backedUpTo = `${envFile}.managed-backup-${stamp}`;
      copyFileSync(envFile, backedUpTo);
    }
  }

  mkdirSync(path.dirname(envFile), { recursive: true });
  writeFileSync(envFile, content, 'utf8');
  return { envFile, wrote: true, backedUpTo };
}

export function localProfileSummary(status, envFile) {
  return [
    `App (when Vite is running): ${DEFAULT_APP_URL}`,
    `Supabase API: ${status.API_URL}`,
    `Studio: ${status.STUDIO_URL}`,
    `Mailpit: ${status.MAILPIT_URL ?? status.INBUCKET_URL}`,
    `Frontend env file: ${path.relative(repoRoot, envFile)}`,
  ];
}

export function sqlLiteral(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

export async function prepareLocalProfile(options = {}) {
  ensureDocker();
  if (options.recreateStack) {
    stopSupabase({ noBackup: true });
  }
  startSupabase();
  if (!options.skipReset) {
    resetLocalDatabase();
  }

  const status = getSupabaseStatus();
  const envResult = writeLocalEnvFile(status, {
    envFile: options.envFile,
    write: options.writeEnv !== false,
    forceEnv: options.forceEnv,
    backupManagedEnv: options.backupManagedEnv,
  });

  return {
    status,
    envFile: envResult.envFile,
    wroteEnv: envResult.wrote,
    backedUpTo: envResult.backedUpTo,
  };
}

export function printLocalProfileSummary(result) {
  logStep('Local profile ready');
  for (const line of localProfileSummary(result.status, result.envFile)) {
    logInfo(line);
  }
  if (result.backedUpTo) {
    logInfo(
      `Managed env backed up to: ${path.relative(repoRoot, result.backedUpTo)}`,
    );
  }
}
